In [ ]:
!pip install pandas
!pip install numpy
!pip install nltk

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [ ]:
#untuk komputasi numerik
import numpy as np

#memproses pengolahan text
import nltk

#membantu mempermudah manipulasi data teks
import string

#mencari pola akta spesifik yang dicari
import re

#hilangkan notif karena migrasi dari python
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import pandas as pd
from tqdm import tqdm, notebook
import warnings
warnings.filterwarnings('ignore')

pd.pandas.set_option('display.max_columns', None)
pd.pandas.set_option('display.max_rows', None)
pd.pandas.set_option('display.max_colwidth', None)
pd.pandas.set_option('display.width', None)

In [ ]:
df = pd.read_csv('/content/DataSetMyTelkkomsel.csv')
df.head()

,userName,score,at,content
0,Pengguna Google,5,2026-06-01 04:20:51,Sangat bagus fiturnya banyak.
1,Pengguna Google,5,2026-06-01 04:20:26,terbaik
2,Pengguna Google,1,2026-06-01 04:18:27,aplikasinya lemot dan eror
3,Pengguna Google,5,2026-06-01 04:15:32,nice
4,Pengguna Google,1,2026-06-01 04:09:27,"Lolaaaaaaa banget aplikasi ini, kita mau lbeli paketnyaa loadingnya minta ampun. Kebanyakan kerjasama.. aplikasinya fokus jualan paket aja bisa ga sih!!!!! notifikasi berulang2 ""anda tidak terhubung di internet,"" alamak Bar Sinyal Telkomsel Full woy.. Benerbener makin kesini makin PARAH."

In [ ]:
df['sentiment'] = df['score'].map({1.0:0, 2.0:0, 3.0:1, 4.0:1, 5.0:1})

In [ ]:
dataku = pd.DataFrame(df[['content', 'sentiment']])
dataku.head(10)

,content,sentiment
0,Sangat bagus fiturnya banyak.,1
1,terbaik,1
2,aplikasinya lemot dan eror,0
3,nice,1
4,"Lolaaaaaaa banget aplikasi ini, kita mau lbeli paketnyaa loadingnya minta ampun. Kebanyakan kerjasama.. aplikasinya fokus jualan paket aja bisa ga sih!!!!! notifikasi berulang2 ""anda tidak terhubung di internet,"" alamak Bar Sinyal Telkomsel Full woy.. Benerbener makin kesini makin PARAH.",0
5,terimakasih,1
6,baik,1
7,paket all varian murce lohhh 🫶🤗,1
8,Harga Paket yang ada terus berubah ubah tiap 2 hingga sebulan sekali. dan setiap kali berubah selalu semakin mahal.,0
9,sangat baik,1

In [ ]:
my_df = dataku[['content', 'sentiment']]

In [ ]:
my_df.to_csv("label_MyTelkomsel.csv", index = False)