INSTALL LIBRARY

In [5]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 474.3 kB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [2]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

IMPORT LIBRARY

In [6]:
from google_play_scraper import app
import pandas as pd
import numpy as np

In [7]:
from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.telkomsel.telkomselcm',
    lang = 'id',
    country = 'id',
    sort = Sort.NEWEST,
    count = 8000,
    filter_score_with = None
)

SHOW DATA YANG SUDAH DI CRAWLING

In [8]:
df_busu = pd.DataFrame(np.array(result), columns = ['review'])
df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))
df_busu.tail()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
7995,daf9c76d-eada-4bf9-be77-7c60cc0deeef,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Saya pengguna dari 2008 sampai sekarang, tapi ...",1,1,9.2.0,2026-05-12 06:50:48,"Hai Kak Sujati, Mohon maaf untuk ketidaknyaman...",2026-05-12 08:26:14,9.2.0
7996,330f1e80-ba60-4dc4-bd72-c75ec075606e,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,pembelian paket internet 65000 pembayaran qris...,1,0,9.2.0,2026-05-12 06:45:12,"Hai Kak Eko, Mohon maaf untuk ketidaknyamanann...",2026-05-12 08:17:56,9.2.0
7997,4164a303-7459-4c19-93f7-528e2e7042a0,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,mantap mudah kalau isi paket GK perlu keluar r...,5,0,9.2.0,2026-05-12 06:43:27,None,NaT,9.2.0
7998,cc36e9a0-389f-4ea4-ac58-5fc168db8cb4,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Banyak korupsi nya ini Telkomsel. dari masa te...,2,0,None,2026-05-12 06:42:48,Hai Kak Jt. Mohon maaf untuk ketidaknyamananny...,2026-05-12 11:15:02,None
7999,8583bfc3-7df9-4d8b-8b61-c48039a30431,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Telkomsel ini kenapa jaringannya di riau lelet...,1,1,9.2.0,2026-05-12 06:41:49,"Hai Kak Rosdiana, Mohon maaf untuk ketidaknyam...",2026-05-12 08:17:21,9.2.0

AMBIL DATA YANG DIBUTUHKAN

In [9]:
df_busu[['userName', 'score', 'at', 'content']].tail()

,userName,score,at,content
7995,Pengguna Google,1,2026-05-12 06:50:48,"Saya pengguna dari 2008 sampai sekarang, tapi ..."
7996,Pengguna Google,1,2026-05-12 06:45:12,pembelian paket internet 65000 pembayaran qris...
7997,Pengguna Google,5,2026-05-12 06:43:27,mantap mudah kalau isi paket GK perlu keluar r...
7998,Pengguna Google,2,2026-05-12 06:42:48,Banyak korupsi nya ini Telkomsel. dari masa te...
7999,Pengguna Google,1,2026-05-12 06:41:49,Telkomsel ini kenapa jaringannya di riau lelet...

In [10]:
my_df = df_busu[['userName', 'score', 'at', 'content']]

In [11]:
#simpan dataset e dalam file
my_df.to_csv("DataSetMyTelkkomsel.csv", index = False)